apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: demo-app-config-prd
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  secretRef:
    name: demo-app
  url: https://github.exampledomain.com/tanthanhkid/eksa-demo-app.git
